groups:
- name: fraud-api-alerts
  rules:
  - alert: FraudAPIDown  # Fraud API Down Alert
    expr: up{job="fraud_api"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Fraud API Down"
      description: "Fraud detection API is down for more than 1 minute"

  - alert: HighContainerCPU
    expr: rate(container_cpu_usage_seconds_total{job="cadvisor", id=~"/docker/.+"}[1m]) > 0.8
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "High container CPU usage detected"
      description: "Container CPU usage exceeded 80% for more than 30 seconds."


  - alert: HighContainerMemory
    expr: container_memory_usage_bytes{id=~"/docker/342e223da83f.*"} > 150000000
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "High Memory Usage (Fraud API)"
      description: "Fraud API container memory usage exceeded threshold."


  - alert: HighFraudAPILatency
    expr: histogram_quantile(
            0.95,
            sum(rate(http_request_duration_seconds_bucket{job="fraud_api"}[5m])) by (le)
          ) > 2
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "High Fraud API Latency"
      description: "95% of Fraud API requests are taking more than 2 seconds"


  - alert: HighPredictionLatencyP95 # Prediction Latency Alert (P95)
    expr: histogram_quantile(
            0.95,
            sum by (le) (
              rate(prediction_latency_seconds_bucket[5m])
            )
          ) > 0.2
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "High Prediction Latency (P95)"
      description: "95% fraud predictions taking more than 1 second"

  - alert: HighFraudAPIErrorRate
    expr: (
            sum(rate(http_requests_total{job="fraud_api", status=~"5.."}[1m]))
            /
            sum(rate(http_requests_total{job="fraud_api"}[1m]))
          ) > 0.05
    for: 30s
    labels:
      severity: critical
    annotations:
      summary: "High Fraud API Error Rate"
      description: "5xx error rate exceeded 5%"

  - alert: HighMerchantChargebackRate # Merchant chargeback rate
    expr: fraud_merchant_chargeback_rate > 0.03
          AND fraud_merchant_total_transactions > 100
    for: 15m
    labels:
      severity: high
    annotations:
      summary: "High merchant chargeback rate with significant volume"
      description: "Merchant chargeback rate exceeded 3% with more than 100 transactions for 15 minutes."


  - alert: HighBINFailureRate
    expr: fraud_bin_failure_rate > 0.50
          AND fraud_bin_total_transactions > 100
    for: 15m
    labels:
      severity: medium
    annotations:
      summary: "High BIN failure rate with significant volume"
      description: "BIN failure rate exceeded 10% with more than 100 transactions for 15 minutes."








