global:
  scrape_interval: 5s

rule_files:
  - "alert.rules.yml"

scrape_configs:
  - job_name: "fraud_api"
    static_configs:
      - targets: ["fraud-api:8000"]
    metrics_path: /metrics

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

